### ISSUE TITLE
bug unhandled rejection error with chrome

### ISSUE THREAD

**Issue by cnishina** [cnishina/webdriver-manager-replacement#100]
```
webdriver-manager-replacement update --gecko=false --out_dir=downloads --versions.chrome=71.0.3578.80
/Users/craignishina/src/protractor-lite/node_modules/webdriver-manager-replacement/downloads
curl -o /Users/craignishina/src/protractor-lite/downloads/selenium-server-standalone-3.141.59.jar https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
(node:83818) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getVersionObj (/Users/craignishina/src/protractor-lite/node_modules/webdriver-manager-replacement/dist/lib/provider/utils/version_list.js:49:31)
    at Object.getVersion (/Users/craignishina/src/protractor-lite/node_modules/webdriver-manager-replacement/dist/lib/provider/utils/version_list.js:13:12)
    at ChromeDriver.updateBinary (/Users/craignishina/src/protractor-lite/node_modules/webdriver-manager-replacement/dist/lib/provider/chromedriver.js:62:43)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
(node:83818) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:83818) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by cnishina** [comment]
Fixed with https://github.com/cnishina/webdriver-manager-replacement/commit/96f13fe3fdd5441c014604f33f2cbd0c49565c86.
