### ISSUE TITLE
Avoid using symbolic links for binaries

### ISSUE THREAD

**Issue by cnishina** [cnishina/webdriver-manager-replacement#2]
On windows tried to launch git-web-launcher and the error message is as follows:

```
D:\src\git-web-launcher\lib>web chrome_launch.ts
curl -o D:\Users\cnishina\AppData\Roaming\nvm\v8.11.3\node_modules\git-web-launcher\downloads\chromedriver.xml https://chromedriver.storage.googleapis.com/
curl -o D:\Users\cnishina\AppData\Roaming\nvm\v8.11.3\node_modules\git-web-launcher\downloads\chromedriver_win32.zip https://chromedriver.storage.googleapis.com/2.40/chromedriver_win32.zip
unlink: D:\Users\cnishina\AppData\Roaming\nvm\v8.11.3\node_modules\git-web-launcher\downloads\chromedriver.exe
add symbolic link: D:\Users\cnishina\AppData\Roaming\nvm\v8.11.3\node_modules\git-web-launcher\downloads\chromedriver.exe
for: D:\Users\cnishina\AppData\Roaming\nvm\v8.11.3\node_modules\git-web-launcher\downloads\chromedriver_2.40.exe
Error: The specified executable path does not exist: D:\Users\cnishina\AppData\Roaming\nvm\v8.11.3\node_modules\git-web-launcher\downloads\chromedriver
    at new DriverService.Builder (D:\Users\cnishina\AppData\Roaming\nvm\v8.11.3\node_modules\git-web-launcher\node_modules\selenium-webdriver\remote\index.js:319:13)
    at new ServiceBuilder (D:\Users\cnishina\AppData\Roaming\nvm\v8.11.3\node_modules\git-web-launcher\node_modules\selenium-webdriver\chrome.js:239:5)
    at Object.<anonymous> (D:\Users\cnishina\AppData\Roaming\nvm\v8.11.3\node_modules\git-web-launcher\dist\chrome_launch.js:55:27)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Users\cnishina\AppData\Roaming\nvm\v8.11.3\node_modules\git-web-launcher\dist\chrome_launch.js:4:58)
    at <anonymous>

```

The error message looks like symbolic links do not work. Maybe we keep track of the binary locations in a file.

**Comment by cnishina** [comment]
Update file_utils with 0bdc63997d4088697111fbf545cf84c2242f84be.
