### ISSUE TITLE
fix flaky cloud_storage_xml test

### ISSUE THREAD

**Issue by cnishina** [cnishina/webdriver-manager-replacement#95]
cloud_storage_xml with a http server updateXml should request and write the file if it is expired

Sample error:
```
Failures:
1) cloud_storage_xml with a http server updateXml should request and write the file if it is expired
  Message:
    Expected 510 to be greater than 510.
  Stack:
    Error: Expected 510 to be greater than 510.
        at <Jasmine>
        at UserContext.it (/home/circleci/workspace/dist/lib/provider/utils/cloud_storage_xml.spec-int.js:106:26)
        at <Jasmine>
        at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by cnishina** [comment]
Possibly resolved with https://github.com/cnishina/webdriver-manager-replacement/pull/96
